#!/usr/bin/env python3
"""Verify the pinned foundation and content boundary; no third-party Python packages required."""
from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import random
import shutil
import subprocess
import sys
import tempfile
import time
import wave

ROOT = Path(__file__).resolve().parent.parent
BUILD = ROOT / 'build'
EVIDENCE = BUILD / 'evidence'
ENV = dict(os.environ, BEND_NO_TELEMETRY='1', PATH=str(ROOT / 'scripts') + os.pathsep + os.environ.get('PATH', ''))
RESULTS: list[dict] = []


def run(name, argv, *, expected=0, output=None, contains=None, cwd=ROOT, env=ENV, timeout=90):
    start = time.monotonic()
    result = subprocess.run([str(a) for a in argv], cwd=cwd, env=env,
                            text=True, capture_output=True, timeout=timeout)
    ok = result.returncode == expected if expected is not None else result.returncode != 0
    if output is not None:
        ok = ok and result.stdout.strip() == output
    if contains is not None:
        ok = ok and contains in result.stdout + result.stderr
    RESULTS.append({'name': name, 'passed': ok, 'exitCode': result.returncode,
                    'seconds': round(time.monotonic() - start, 3)})
    (EVIDENCE / f'{len(RESULTS):03d}.log').write_text(
        f'{name}\ncommand: {argv!r}\nexit: {result.returncode}\n'
        + result.stdout + result.stderr, encoding='utf-8')
    if not ok:
        raise RuntimeError(f'{name} failed (exit {result.returncode})\n{result.stdout}{result.stderr}')
    return result


def main():
    BUILD.mkdir(exist_ok=True)
    EVIDENCE.mkdir(exist_ok=True)
    # All log files are generated by this script; start a fresh evidence set.
    for path in EVIDENCE.glob('*.log'):
        path.unlink()
    if not shutil.which('node'):
        raise RuntimeError('Node.js is required for the JavaScript differential fixture')
    run('toolchain pin', [sys.executable, ROOT / 'scripts/setup_toolchain.py'])
    run('version', ['bend', '--version'], output='bend 2.0.19')
    # This is the canonical law gate, invoking the workspace-pinned bend.
    run('canonical proof gate', ['bend', 'PROOF.bend'], contains='All terms check.')
    run('false law must fail', ['bend', 'tests/feasibility/false_law.bend'], expected=None, contains='Error:')
    run('open law must fail', ['bend', 'tests/feasibility/open_law.bend'], expected=None, contains='TODO')
    for base in ['engine', 'platform', 'tests/feasibility', 'tests/content']:
        for path in sorted((ROOT / base).rglob('*.bend')):
            if path.name in {'false_law.bend', 'open_law.bend'}:
                continue
            run('check ' + str(path.relative_to(ROOT)), ['bend', path, '--check-only'])
    run('native headless build', ['bend', 'platform/feasibility/headless.bend', '-o', BUILD / 'headless'])
    run('JS headless build', ['bend', 'platform/feasibility/headless.bend', '-o', BUILD / 'headless.js'])
    examples = [[], ['0'], ['1', '2', '3'], ['0001', '2'], ['4294967295', '1'], ['4294967295'] * 1024]
    generator = random.Random(1977)
    examples += [[str(generator.randrange(0, 2**32)) for _ in range(generator.randrange(1, 24))] for _ in range(20)]
    for i, args in enumerate(examples):
        expected = str(sum(map(int, args)))
        run(f'native sum {i}', [BUILD / 'headless', '--threads', '1', '--', *args], output=expected)
        run(f'JS sum {i}', ['node', BUILD / 'headless.js', '--', *args], output=expected)
    invalid = [['-1'], ['4294967296'], ['+1'], ['1.0'], ['1x'], [''], [' 1'], ['1\n'], ['0'] * 1025]
    for i, args in enumerate(invalid):
        for target, command in [('native', [BUILD / 'headless']), ('JS', ['node', BUILD / 'headless.js'])]:
            run(f'{target} reject {i}', [*command, '--', *args], expected=2, contains='unsigned decimal U32')
    run('parallel native build', ['bend', 'tests/feasibility/parallel_cpu.bend', '-o', BUILD / 'parallel_cpu'])
    for threads in [1, 2, 4]:
        run(f'parallel determinism {threads} threads', [BUILD / 'parallel_cpu', '--threads', str(threads), '--gpu', 'off'], output='262144')
    # A clean directory and PATH without Bend verifies the binary needs no compiler.
    with tempfile.TemporaryDirectory(prefix='bend-distribution.') as temp:
        binary = Path(temp) / 'headless'
        shutil.copy2(BUILD / 'headless', binary)
        run('compiler-free binary', [binary, '--', '100', '23'], output='123', cwd=temp,
            env={'PATH': '/usr/bin:/bin', 'LANG': 'C'})
    run('presentation boundary suite', ['sh', 'tests/feasibility/presentation/run.sh'])
    run('presentation build', ['bend', 'platform/feasibility/presentation/main.bend', '-o', BUILD / 'presentation'])
    artifacts = EVIDENCE / 'presentation'
    artifacts.mkdir(exist_ok=True)
    run('presentation artifacts', [BUILD / 'presentation', artifacts], contains='tone.wav')
    with wave.open(str(artifacts / 'tone.wav'), 'rb') as tone:
        assert (tone.getnchannels(), tone.getsampwidth(), tone.getframerate(), tone.getnframes()) == (1, 2, 22050, 3969)
    hashes = {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(artifacts.iterdir()) if p.suffix in {'.ppm', '.wav'}}
    (EVIDENCE / 'artifact-hashes.json').write_text(json.dumps(hashes, indent=2) + '\n')
    run('native content kernel build', ['bend', 'platform/content/kernel.bend', '-o', BUILD / 'content-kernel'])
    run('content kernel and loader regression suite', [sys.executable, '-m', 'unittest', 'discover', '-s', 'tests/content', '-p', 'test_*.py', '-v'], timeout=180)
    run('generated XP table is current', [sys.executable, 'scripts/generate_xp_table.py', '--check'])
    run('M1 architecture contract suite', [sys.executable, '-m', 'unittest',
        'discover', '-s', 'tests/architecture', '-t', '.', '-p', 'test_*.py', '-v'])
    run('rules regression suite', [sys.executable, '-m', 'unittest', 'discover', '-s', 'tests/rules', '-p', 'test_*.py', '-v'])
    run('battle fixture regression suite', [sys.executable, '-m', 'unittest', 'discover', '-s', 'tests/battle', '-t', '.', '-p', 'test_*.py', '-v'])
    run('battle scheduler golden', ['bend', 'tests/battle/scheduler_test.bend'], output='[1n, 1n, 1n, 1n]')
    run('battle reducer golden', ['bend', 'tests/battle/reducer_test.bend'], output='[1n, 1n, 1n, 1n]')
    run('battle RNG golden', ['bend', 'tests/battle/rng_test.bend'], output='[1n, 1n, 1n, 1n, 1n]')
    run('battle combat math golden', ['bend', 'tests/battle/combat_math_test.bend'], output='[1n, 1n, 1n, 1n, 1n, 1n]')
    run('battle combat resolver golden', ['bend', 'tests/battle/combat_resolver_test.bend'], output='[1n, 1n, 1n, 1n, 1n, 1n, 1n]')
    # The interpreter can exhaust its machine stack on hosted runners for this
    # recursive roster fixture. Compile the same production golden and run the
    # native result with one worker, as the distribution path does.
    run('battle roster native build', ['bend', 'tests/battle/roster_test.bend',
        '-o', BUILD / 'roster_test'])
    run('battle roster golden', [BUILD / 'roster_test', '--threads', '1',
        '--gpu', 'off'], output='[1n, 1n, 1n, 5000n, 1000n, 9500n]')
    run('battle participants golden', ['bend', 'tests/battle/participants_test.bend'], output='[1n, 1n, 1n]')
    run('battle sources golden', ['bend', 'tests/battle/sources_test.bend'], output='[1n, 1n, 1n, 1n]')
    run('battle driver golden', ['bend', 'tests/battle/driver_test.bend'], output='[1n, 1n, 1n]')
    run('battle runtime golden', ['bend', 'tests/battle/runtime_test.bend'], output='[1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n]')
    run('battle effect runtime golden', ['bend', 'tests/battle/runtime_effect_test.bend'], output='[31n, 1n, 1n, 11n, 1n]')
    run('battle effect algebra golden', ['bend', 'tests/battle/effects_test.bend'], output='[1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n]')
    # The exact-rational M5 golden compiles in roughly 70 seconds locally and
    # needs the same hosted-runner allowance as the replay differential group.
    run('M5 multi-type golden', ['bend', 'tests/m5/multi_type_test.bend'],
        output='[1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n]', timeout=180)
    run('M5 fixture and cross-target suite', [sys.executable, '-m', 'unittest',
        'discover', '-s', 'tests/m5', '-t', '.', '-p', 'test_*.py', '-v'], timeout=180)
    run('M6 recipe core golden', ['bend', 'tests/m6/recipe_test.bend'],
        output='[1n, 1n, 1n, 1n, 1n, 1n, 1n]')
    run('M6 mixed source transaction golden',
        ['bend', 'tests/m6/mixed_sources_test.bend'],
        output='[1n, 1n, 1n, 1n, 1n, 1n]')
    run('M6 Harmony core golden', ['bend', 'tests/m6/harmony_test.bend'],
        output='True{}')
    run('M6 eligibility core golden', ['bend', 'tests/m6/eligibility_test.bend'],
        output='[True{}, True{}, True{}, True{}]')
    run('M6 learning core golden', ['bend', 'tests/m6/learning_test.bend'],
        output='[1n, 1n, 1n, 1n, 1n]')
    run('M6 mixed runtime golden', ['bend', 'tests/m6/mixing_runtime_test.bend'],
        output='[1n, 0n, 1n, 1n, 1n, 1n, 1n, 1n]')
    run('M6 learning ledger golden', ['bend', 'tests/m6/ledger_test.bend'],
        output='True{}')
    run('M6 mixed runtime and learning driver golden',
        ['bend', 'tests/m6/driver_test.bend'],
        output='[1n, 1n, 1n, 1n, 1n, 1n]', timeout=180)
    run('M6 pure fixture and cross-target suite', [sys.executable, '-m',
        'unittest', 'tests.m6.test_core_fixtures',
        'tests.m6.test_cross_target_core', '-v'], timeout=180)
    run('battle replay fold golden', ['bend', 'tests/replay/fold_test.bend'], output='[1n, 1n, 1n, 1n]')
    run('battle runtime replay golden', ['bend', 'tests/replay/runtime_fold_test.bend'], output='[1n, 1n, 1n]')
    run('battle effect replay golden', ['bend', 'tests/replay/runtime_effect_fold_test.bend'], output='[1n]')
    run('persistence boundary regression suite', [sys.executable, '-m', 'unittest', 'discover', '-s', 'tests/persistence', '-p', 'test_*.py', '-v'])
    # Runtime cross-target compilation is intentionally part of this suite and
    # takes about 85 seconds on the reference workstation. Give slower hosted
    # runners the same bounded allowance used by the content regression group.
    run('replay checkpoint regression suite', [sys.executable, '-m', 'unittest', 'discover', '-s', 'tests/replay', '-p', 'test_*.py', '-v'], timeout=180)
    result = run('original project loads through Bend', [sys.executable, 'scripts/validate_project.py', 'examples/original-demo'])
    loaded = json.loads(result.stdout)
    assert loaded['ok'] is True and len(loaded['contentHash']) == 64
    (EVIDENCE / 'content-project.json').write_text(json.dumps(loaded, indent=2) + '\n')
    print(f'PASS: {len(RESULTS)} checks; laws, native/JS boundaries, CPU parallelism, presentation, content and milestone fixtures.')


if __name__ == '__main__':
    try:
        main()
    except (RuntimeError, subprocess.TimeoutExpired, OSError, AssertionError) as error:
        print(f'FAIL: {error}', file=sys.stderr)
        sys.exit(1)
    finally:
        EVIDENCE.mkdir(parents=True, exist_ok=True)
        (EVIDENCE / 'verification.json').write_text(json.dumps({'checks': RESULTS, 'scope': 'foundation, content-0 loading and milestone support artifacts; not full gameplay verification'}, indent=2) + '\n')
